version: '3'
services:
  solr:
    container_name: solr_prevent
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - logIndex

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres

    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "5432:5432"
    restart: always


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@preventsenior.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass preventSenior2021
    hostname: redis
    ports:
      - "6379:6379"

  prevent:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "8080-8081:8082"
    depends_on:
      - postgres
      - redis
      - solr
      - pgadmin
    restart: unless-stopped